site_name: SciComp @ RU

plugins:
  - search
  - blogging:
      dirs:
        - posts

markdown_extensions:
  - meta

nav:
  - Home: index.md
  - News: news.md
  - Contributing: contributions.md

site_url: https://scicomp.ru.is
