site_name: SciComp @ RU
site_description: Scientific Computing and HPC at Reykjavík University

plugins:
  - search
  - blogging:
      dirs:
        - posts
  - rss:
      match_path: posts/.*
      date_from_meta:
        as_creation: date

markdown_extensions:
  - meta

nav:
  - Home: index.md
  - Documentation: docs.md
  - News: news.md
  - Contributing: contributions.md

site_url: https://scicomp.ru.is
